In [2]:
#Reading excel data from python
import pandas as pd
#df = pd.read_excel(r'C:\Users\laksh\OneDrive\Desktop\NumpyNinja\Python\Python Hackathon\HospitalDatabase.xlsx')
xl = pd.ExcelFile(r'C:\Users\laksh\OneDrive\Desktop\NumpyNinja\Python\Python Hackathon\HospitalDatabase.xlsx')
sheets = xl.sheet_names
for i, sheet in enumerate(sheets):
    globals()['df'+ str(i+1)] = pd.read_excel(r'C:\Users\laksh\OneDrive\Desktop\NumpyNinja\Python\Python Hackathon\HospitalDatabase.xlsx', sheet_name = sheet)
print(df1)
print(df2)
print(df3)
print(df4)
print(df5)
print(df6)
print(df7)

     PatientID FirstName  LastName             DateOfBirth Gender  \
0            1     Lanni       Sue 1960-01-01 00:00:00.000   Male   
1            2       Far     Myers 1985-11-15 02:08:42.090   Male   
2            3   Devlin    Michael 1976-04-15 02:52:09.762   Male   
3            4   Carmine     Texas 1968-10-15 03:32:13.635   Male   
4            5     Tann       Bama 1962-05-01 19:12:58.950   Male   
..         ...       ...       ...                     ...    ...   
940        941       Wat   Fideler 1986-05-26 00:01:19.761   Male   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   Male   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   Male   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   Male   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   Male   

                       Race Language  
0                     White  English  
1                     White  English  
2                     White  English  
3              

In [3]:
#Q61: np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17.

import numpy as np
 
myArray1 = np.arange (1,31)
myArray2 = myArray1.reshape(6, 5)

print (myArray1)
print (myArray2)

# How to get elements with values 11, 12, 16 and 17

# 11, Row 3 column 1, substract 1 to get the array index
print(myArray2[2, 0])

#12, Row 3 column 2
print(myArray2[2, 1])


#16, Row 4 column 1
print(myArray2[3, 0])


#17, Row 4 column 2
print(myArray2[3, 1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
11
12
16
17


In [4]:
#Q62: Create a dataframe with acuity and EDDisposition as the indices and the count of number of patients as the value.

import pandas as pd

df = pd.read_excel(r'C:\Users\laksh\OneDrive\Desktop\NumpyNinja\Python\Python Hackathon\HospitalDatabase.xlsx', sheet_name='EDVisits')
df = df[['Acuity','EDDisposition','PatientID']]
#df.groupby('Acuity')['EDDisposition'].count().reset_index(name='CountOfPatients')
#df.groupby(['Acuity'],['EDDisposition'])['EDDisposition'].count().reset_index(name='Count')
df.groupby(['Acuity','EDDisposition'])['EDDisposition'].count().reset_index(name='CountOfPatients')

Acuity EDDisposition  CountOfPatients
0       1      Admitted               32
1       1    Discharged              558
2       2      Admitted              116
3       2    Discharged               66
4       3      Admitted               81
5       4      Admitted              107
6       4    Discharged               30
7       5      Admitted              179
8       5    Discharged               30

In [5]:
#63: List male patients over the age of 60 who have undergone surgery from January-March 2019.
# First adding Age column

from datetime import date, datetime
# This function converts given date to age
def age(born):
    today = date.today()
    return today.year - born.year - ((today.month, 
                                      today.day) < (born.month, 
                                                    born.day))
 
df1['Age'] = df1['DateOfBirth'].apply(age)
#df1A

new = df1[df1['Gender']=='Male']
new1 = new[new['Age']>60]
surgery = df6[df6['ProviderSpecialty'] == 'Surgery']
new1[df3['ProviderID'].isin(surgery['ProviderID'])]


C:\Users\laksh\AppData\Local\Temp\ipykernel_13100\271524971.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  new1[df3['ProviderID'].isin(surgery['ProviderID'])]


PatientID  FirstName   LastName             DateOfBirth Gender  \
18          19  Daugherty     Conner 1960-04-04 10:00:34.189   Male   
150        151      Levon   Bonifant 1960-12-17 15:28:38.898   Male   
203        204    Gerhold    Cockett 1961-06-06 16:19:37.115   Male   
216        217   Gratiana      Group 1961-10-08 14:54:58.793   Male   
425        426       Bins    Garbutt 1961-12-30 23:52:41.522   Male   
443        444       Isis  Grimditch 1960-03-01 01:11:11.217   Male   
482        483       Angy     Hassen 1961-10-24 16:24:56.342   Male   
559        560      Robyn   Aucourte 1960-02-11 20:56:05.193   Male   
716        717       Hahn      Baudy 1961-03-02 06:09:40.630   Male   

                       Race Language  Age  
18                    White  Spanish   63  
150  Black/African-American  English   62  
203  Black/African-American  English   61  
216  Black/African-American  English   61  
425                   White  English   61  
443                   White  English   63  
482  Black/African-American  English   61  
559  Black/African-American  English   63  
716                   White  English   62